logging:
  level:
    root: warn
    com.rest.api: info
  path: D:/study/Demo/springboot-vue-riding/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://192.168.0.50/matrix_hhw?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: matrix_hhw
    password: matrix_hhw
  jwt:
    secrect: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  url:
    base: http://localhost:8086