spring:
  profiles:
    active: local # 디폴트 환경
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    static-path-pattern: /dist/**
  resources:
    add-mappings: true
    static-locations: classpath:/dist/
  social:
    kakao:
      client_id: 4d17665499de45f706d8482e0e240aae # 앱생성시 받은 REST API 키
      redirect: /api/social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  jwt:
    secrect: test